* Makefile.am (windows-dist): Create a 7z compressed Windows comprehensive source package.  See http://www.7-zip.org/ for information on Windows 7-Zip and http://p7zip.sourceforge.net/ for information on portable 7-Zip (P7ZIP).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1102,6 +1102,12 @@ ShowImageDelegate
 RPM
 HAS_RPM_TRUE
 HAS_RPM_FALSE
+P7ZIP
+HAS_P7ZIP_TRUE
+HAS_P7ZIP_FALSE
+ZIP
+HAS_ZIP_TRUE
+HAS_ZIP_FALSE
 GSMonoDevice
 GSGrayDevice
 GSColorDevice
@@ -6743,13 +6749,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6746: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6752: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6749: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:6755: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:6752: output\"" >&5)
+  (eval echo "\"\$as_me:6758: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7846,7 +7852,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7849 "configure"' > conftest.$ac_ext
+  echo '#line 7855 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9462,11 +9468,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9465: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9471: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9469: \$? = $ac_status" >&5
+   echo "$as_me:9475: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9780,11 +9786,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9783: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9789: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9787: \$? = $ac_status" >&5
+   echo "$as_me:9793: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9885,11 +9891,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9888: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9894: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9892: \$? = $ac_status" >&5
+   echo "$as_me:9898: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9940,11 +9946,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9943: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9949: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9947: \$? = $ac_status" >&5
+   echo "$as_me:9953: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12687,7 +12693,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12690 "configure"
+#line 12696 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12787,7 +12793,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12790 "configure"
+#line 12796 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15507,11 +15513,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15510: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15516: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15514: \$? = $ac_status" >&5
+   echo "$as_me:15520: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15606,11 +15612,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15609: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15615: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15613: \$? = $ac_status" >&5
+   echo "$as_me:15619: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15658,11 +15664,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15661: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15667: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15665: \$? = $ac_status" >&5
+   echo "$as_me:15671: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17452,7 +17458,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 17455 "configure"
+#line 17461 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -38570,7 +38576,7 @@ fi
 
 
 #
-# RedHat RPM support
+# RedHat RPM support (http://rpm5.org/)
 #
 RPM=''
 for ac_prog in rpmbuild rpm
@@ -38622,6 +38628,118 @@ done
 else
   HAS_RPM_TRUE='#'
   HAS_RPM_FALSE=
+fi
+
+
+#
+# 7ZIP support (http://p7zip.sourceforge.net/)
+#
+P7ZIP=''
+for ac_prog in 7za
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_P7ZIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$P7ZIP"; then
+  ac_cv_prog_P7ZIP="$P7ZIP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_P7ZIP="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+P7ZIP=$ac_cv_prog_P7ZIP
+if test -n "$P7ZIP"; then
+  { echo "$as_me:$LINENO: result: $P7ZIP" >&5
+echo "${ECHO_T}$P7ZIP" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$P7ZIP" && break
+done
+
+
+ if test "x$P7ZIP" != "x" ; then
+  HAS_P7ZIP_TRUE=
+  HAS_P7ZIP_FALSE='#'
+else
+  HAS_P7ZIP_TRUE='#'
+  HAS_P7ZIP_FALSE=
+fi
+
+
+#
+# ZIP support (http://www.info-zip.org/Zip.html)
+#
+ZIP=''
+for ac_prog in zip
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_ZIP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$ZIP"; then
+  ac_cv_prog_ZIP="$ZIP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_ZIP="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+ZIP=$ac_cv_prog_ZIP
+if test -n "$ZIP"; then
+  { echo "$as_me:$LINENO: result: $ZIP" >&5
+echo "${ECHO_T}$ZIP" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$ZIP" && break
+done
+
+
+ if test "x$ZIP" != "x" ; then
+  HAS_ZIP_TRUE=
+  HAS_ZIP_FALSE='#'
+else
+  HAS_ZIP_TRUE='#'
+  HAS_ZIP_FALSE=
 fi
 
 
@@ -39466,6 +39584,20 @@ if test -z "${HAS_RPM_TRUE}" && test -z "${HAS_RPM_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAS_RPM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAS_RPM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAS_P7ZIP_TRUE}" && test -z "${HAS_P7ZIP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAS_P7ZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAS_P7ZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAS_ZIP_TRUE}" && test -z "${HAS_ZIP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAS_ZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAS_ZIP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -40849,6 +40981,12 @@ ShowImageDelegate!$ShowImageDelegate$ac_delim
 RPM!$RPM$ac_delim
 HAS_RPM_TRUE!$HAS_RPM_TRUE$ac_delim
 HAS_RPM_FALSE!$HAS_RPM_FALSE$ac_delim
+P7ZIP!$P7ZIP$ac_delim
+HAS_P7ZIP_TRUE!$HAS_P7ZIP_TRUE$ac_delim
+HAS_P7ZIP_FALSE!$HAS_P7ZIP_FALSE$ac_delim
+ZIP!$ZIP$ac_delim
+HAS_ZIP_TRUE!$HAS_ZIP_TRUE$ac_delim
+HAS_ZIP_FALSE!$HAS_ZIP_FALSE$ac_delim
 GSMonoDevice!$GSMonoDevice$ac_delim
 GSGrayDevice!$GSGrayDevice$ac_delim
 GSColorDevice!$GSColorDevice$ac_delim
@@ -40880,7 +41018,7 @@ ltdl_LIBOBJS!$ltdl_LIBOBJS$ac_delim
 ltdl_LTLIBOBJS!$ltdl_LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 73; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 79; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
