* configure.ac: Test C++ compiler for __func__ support. * magick/log.h: Added GetCurrentFunction() macro to handle __func__ support determination.  Re-wrote GetMagickModule() macro to use GetCurrentFunction().  Changes should allow compilation of Magick++ when the C compiler supports __func__ but the C++ compiler does not. * configure.ac: Changed from using HAS___func__ define to HAS_C__func__ since this feature may be language sensitive.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21596,10 +21596,10 @@ _ACEOF
 
 
 # Test for C compiler __func__ support
-if test "$ac_cv_have___func__" != 'yes' ; then
+if test "$ac_cv_have_C__func__" != 'yes' ; then
 echo "$as_me:$LINENO: checking for C compiler __func__ support" >&5
 echo $ECHO_N "checking for C compiler __func__ support... $ECHO_C" >&6
-if test "${ac_cv_have___func__+set}" = set; then
+if test "${ac_cv_have_C__func__+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -21633,24 +21633,24 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_have___func__='yes'
+  ac_cv_have_C__func__='yes'
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_have___func__='no'
+ac_cv_have_C__func__='no'
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 fi
-echo "$as_me:$LINENO: result: $ac_cv_have___func__" >&5
-echo "${ECHO_T}$ac_cv_have___func__" >&6
+echo "$as_me:$LINENO: result: $ac_cv_have_C__func__" >&5
+echo "${ECHO_T}$ac_cv_have_C__func__" >&6
 
-if test "$ac_cv_have___func__" = 'yes' ; then
+if test "$ac_cv_have_C__func__" = 'yes' ; then
  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
-#define HAS___func__ 1
+#define HAS_C__func__ 1
 _ACEOF
 
 else
@@ -22340,6 +22340,71 @@ ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+  # Test for C++ compiler __func__ support
+ if test "$ac_cv_have_CPP__func__" != 'yes' ; then
+  echo "$as_me:$LINENO: checking for C++ compiler __func__ support" >&5
+echo $ECHO_N "checking for C++ compiler __func__ support... $ECHO_C" >&6
+if test "${ac_cv_have_CPP__func__+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  const char *func=__func__;
+  return 0;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+    ac_cv_have_CPP__func__='yes'
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_CPP__func__='no'
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_CPP__func__" >&5
+echo "${ECHO_T}$ac_cv_have_CPP__func__" >&6
+
+  if test "$ac_cv_have_CPP__func__" = 'yes' ; then
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAS_CPP__func__ 1
+_ACEOF
+
+  else
+   echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+ fi
 
 # Full set of headers used ...
 # algorithm cctype cerrno cmath cstdio cstdlib cstring ctime exception
