Updated configure to use --with-quantum-depth

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1021,7 +1021,6 @@ Optional Features:
   --enable-gcov           enable 'gcov' profiling support (default disabled)
   --disable-largefile     disable support for large (64 bit) file offsets
   --enable-lzw            enable LZW support (default disabled)
-  --disable-16bit-pixel   disable 16 bit/quantum pixels (default enabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1032,6 +1031,7 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-modules          enable support for dynamically loadable modules
+  --with-quantum-depth    number of bits in a pixel quantum (default 16)
   --with-cache            set pixel cache threshhold (default available memory)
   --without-threads       disable threads support
   --with-frozenpaths      enable frozen delegate paths
@@ -18254,14 +18254,24 @@ fi
 
 # Number of bits in a Quantum
 QuantumDepth=16
-# Check whether --enable-16bit-pixel or --disable-16bit-pixel was given.
-if test "${enable_16bit_pixel+set}" = set; then
-  enableval="$enable_16bit_pixel"
-  with_16_bit_pixel=$enableval
+
+# Check whether --with-quantum-depth or --without-quantum-depth was given.
+if test "${with_quantum_depth+set}" = set; then
+  withval="$with_quantum_depth"
+  with_quantum_depth=$withval
 else
-  with_16_bit_pixel='yes'
+  with_quantum_depth=16
 fi;
-test "$with_16_bit_pixel" = 'no' && QuantumDepth=8
+
+case "${with_quantum_depth}" in
+  8 ) ;;
+  16 ) ;;
+  32 ) ;;
+  * ) { { echo "$as_me:$LINENO: error: \"Pixel quantum depth must have value of 8" >&5
+echo "$as_me: error: \"Pixel quantum depth must have value of 8" >&2;}
+   { (exit 16); exit 16; }; } ;;
+esac
+QuantumDepth="$with_quantum_depth"
 
 cat >>confdefs.h <<_ACEOF
 #define QuantumDepth $QuantumDepth
@@ -33941,7 +33951,7 @@ echo "Shared libraries  --enable-shared=$enable_shared    	$libtool_build_shared
 echo "Static libraries  --enable-static=$enable_static    	$libtool_build_static_libs"
 echo "GNU ld            --with-gnu-ld=$with_gnu_ld        	$lt_cv_prog_gnu_ld"
 echo "LZW support       --enable-lzw=$with_lzw            	$with_lzw"
-echo "16 bit pixels     --enable-16bit-pixel=$with_16_bit_pixel 	$with_16_bit_pixel"
+echo "Quantum depth     --with-quantum-depth=$with_quantum_depth 	$with_quantum_depth"
 echo ""
 echo "Delegate Configuration:"
 echo "BZLIB             --with-bzlib=$with_bzlib          	$have_bzlib"
