* magick/magick.c (InitializeMagick): Improved the signal handling and registration method. Signal handlers are only registered for a signal if the current signal handling disposition for that signal is set to the default (SIG_DFL). When a signal is caught, DestroyMagick is invoked, the handling for the signal is set back to SIG_DFL, and then the signal is re-raised to trigger the default handler for that signal. This causes the process to behave as closely to the default as possible (e.g. generating a core file) while ensuring that DestroyMagick is executed. This also ensures that signal handlers registered by API users are not overridden by invoking InitializeMagick. * configure.ac: Added tests for sigemptyset and sigaction. Add a check for the return type of signal handlers. Test for the 'raise' function. * www/formats.html: Add an entry for CUR, Microsoft Cursor Icon format.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26865,6 +26865,70 @@ _ACEOF
 fi
 
 
+# If `signal.h' declares signal as returning a pointer to a function
+# returning void, define RETSIGTYPE to be void; otherwise, define it
+# to be int.
+echo "$as_me:$LINENO: checking return type of signal handlers" >&5
+echo $ECHO_N "checking return type of signal handlers... $ECHO_C" >&6
+if test "${ac_cv_type_signal+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <signal.h>
+#ifdef signal
+# undef signal
+#endif
+#ifdef __cplusplus
+extern "C" void (*signal (int, void (*)(int)))(int);
+#else
+void (*signal ()) ();
+#endif
+
+int
+main ()
+{
+int i;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_signal=void
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_signal=int
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_signal" >&5
+echo "${ECHO_T}$ac_cv_type_signal" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define RETSIGTYPE $ac_cv_type_signal
+_ACEOF
+
+
+
 # Test for C compiler __func__ support
 if test "$ac_cv_have___func__" != 'yes' ; then
 echo "$as_me:$LINENO: checking for C compiler __func__ support" >&5
@@ -27353,8 +27417,12 @@ rm -f conftest.mmap
 
 
 
-for ac_func in ftime getexecname getc_unlocked getpagesize mkstemp poll pread \
-  pwrite putc_unlocked select tempnam times strerror sysconf vsprintf vsnprintf
+
+
+
+for ac_func in ftime getexecname getc_unlocked getpagesize mkstemp poll \
+  pread pwrite putc_unlocked raise select tempnam times sigemptyset sigaction \
+  strerror sysconf vsprintf vsnprintf
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
