* coders/tiff.c (ReadTIFFImage): Support reading TIFF files in IEEEFP format. (WriteTIFFImage): Support writing TIFF files in IEEEFP format. * magick/constitute.c (ExportImagePixelArea): Support exporting floating point data. (ImportImagePixelArea): Support importing floating point data.
* acinclude.m4 (AC_CXX_IOS_BINARY): Added macro to detect if the
C++ compiler lacks support for ios::binary.
* configure.ac: Use  AC_CXX_IOS_BINARY.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24569,6 +24569,85 @@ _ACEOF
 fi
 rm -rf SunWS_cache
 
+ echo "$as_me:$LINENO: checking whether the compiler supports ios::binary" >&5
+echo $ECHO_N "checking whether the compiler supports ios::binary... $ECHO_C" >&6
+if test "${ac_cv_cxx_ios_binary+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <fstream>
+#ifdef HAVE_NAMESPACES
+using namespace std;
+#endif
+int
+main ()
+{
+
+ifstream in( "/dev/null", ios::binary );
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_ios_binary=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_ios_binary=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_ios_binary" >&5
+echo "${ECHO_T}$ac_cv_cxx_ios_binary" >&6
+if test "$ac_cv_cxx_ios_binary" = no; then
+
+cat >>confdefs.h <<\_ACEOF
+#define MISSING_STD_IOS_BINARY
+_ACEOF
+
+fi
+rm -rf SunWS_cache
+
  echo "$as_me:$LINENO: checking whether the compiler supports the mutable keyword" >&5
 echo $ECHO_N "checking whether the compiler supports the mutable keyword... $ECHO_C" >&6
 if test "${ac_cv_cxx_mutable+set}" = set; then
