2002-12-12  Bob Friesenhahn  <bfriesen@simple.dallas.tx.us>         * Enable the module loading code for shared/DLL builds         regardless of whether the build is a "modules" build. This         allows users to add their own modules without requiring the use         of a special "modules" build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MAJOR_VERSION MINOR_VERSION MICRO_VERSION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE PREFIX_DIR EXEC_PREFIX_DIR BIN_DIR SBIN_DIR LIBEXEC_DIR DATA_DIR SYSCONF_DIR SHAREDSTATE_DIR LOCALSTATE_DIR LIB_DIR INCLUDE_DIR OLDINCLUDE_DIR INFO_DIR MAN_DIR WinPathScript CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LD LN_S LIB_GDI32 HasWINGDI32_TRUE HasWINGDI32_FALSE WIN32_NATIVE_BUILD_TRUE WIN32_NATIVE_BUILD_FALSE CYGWIN_BUILD_TRUE CYGWIN_BUILD_FALSE EGREP INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL INCLTDL LIBLTDL ECHO RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS WITH_MODULES_TRUE WITH_MODULES_FALSE DLLDFLAGS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT HasLZW_TRUE HasLZW_FALSE PERL_MAKE_OPTIONS LIBSTDCLDFLAGS MODULE_EXTRA_CPPFLAGS LIBRARY_EXTRA_CPPFLAGS LIB_LF WITH_MAGICK_PLUS_PLUS_TRUE WITH_MAGICK_PLUS_PLUS_FALSE CCMALLOCDelegate LIB_MATH LIB_THREAD HasZLIB_TRUE HasZLIB_FALSE LIB_ZLIB HasBZLIB_TRUE HasBZLIB_FALSE LIB_BZLIB X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HasX11_TRUE HasX11_FALSE LIB_X11 LIB_XEXT LIB_DL HasDPS_TRUE HasDPS_FALSE LIB_DPS HasFPX_TRUE HasFPX_FALSE LIB_FPX HasLCMS_TRUE HasLCMS_FALSE LIB_LCMS HasPNG_TRUE HasPNG_FALSE LIB_PNG HasJPEG_TRUE HasJPEG_FALSE LIB_JPEG HasJP2_TRUE HasJP2_FALSE LIB_JP2 HasGS_TRUE HasGS_FALSE LIB_GS freetype_config HasTTF_TRUE HasTTF_FALSE LIB_TTF HasTIFF_TRUE HasTIFF_FALSE LIB_TIFF HasJBIG_TRUE HasJBIG_FALSE LIB_JBIG xml2_config HasXML_TRUE HasXML_FALSE LIB_XML HasWMF_TRUE HasWMF_FALSE LIB_WMF LIB_WMF_DEPS MagickLibPath MagickModulesPath MagickSharePath AutotraceDecodeDelegate BZIPDelegate BrowseDelegate CGMDecodeDelegate CatDelegate DOTDecodeDelegate DVIDecodeDelegate EchoDelegate EditorDelegate FIGDecodeDelegate GnuplotDecodeDelegate HPGLDecodeDelegate HTMLDecodeDelegate ILBMDecodeDelegate ILBMEncodeDelegate LPDelegate LPRDelegate LZWDecodeDelegate LZWEncodeDelegate LaunchDelegate MANDelegate MPEGDecodeDelegate MPEGEncodeDelegate MVDelegate PGPDecodeDelegate POVDelegate PSDelegate RADDecodeDelegate RLEEncodeDelegate RMDelegate SCANDecodeDelegate TXTDelegate WMFDecodeDelegate WWWDecodeDelegate ZipDelegate PrintDelegate TXT2HTML HasTXT2HTML_TRUE HasTXT2HTML_FALSE windows_font_dir ghostscript_font_dir type_include_files ConvertDelegate MogrifyDelegate ShowImageDelegate GSMonoDevice GSPDFDevice GSPSDevice GSColorDevice GSEPSDevice PERL WITH_PERL_TRUE WITH_PERL_FALSE WITH_PERL_STATIC_TRUE WITH_PERL_STATIC_FALSE WITH_PERL_DYNAMIC_TRUE WITH_PERL_DYNAMIC_FALSE MAGICKLIB DELEGATES MAGICK_DEP_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MAJOR_VERSION MINOR_VERSION MICRO_VERSION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE PREFIX_DIR EXEC_PREFIX_DIR BIN_DIR SBIN_DIR LIBEXEC_DIR DATA_DIR SYSCONF_DIR SHAREDSTATE_DIR LOCALSTATE_DIR LIB_DIR INCLUDE_DIR OLDINCLUDE_DIR INFO_DIR MAN_DIR WinPathScript CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LD LN_S LIB_GDI32 HasWINGDI32_TRUE HasWINGDI32_FALSE WIN32_NATIVE_BUILD_TRUE WIN32_NATIVE_BUILD_FALSE CYGWIN_BUILD_TRUE CYGWIN_BUILD_FALSE EGREP INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL INCLTDL LIBLTDL ECHO RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS WITH_MODULES_TRUE WITH_MODULES_FALSE WITH_LTDL_TRUE WITH_LTDL_FALSE DLLDFLAGS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT HasLZW_TRUE HasLZW_FALSE PERL_MAKE_OPTIONS LIBSTDCLDFLAGS MODULE_EXTRA_CPPFLAGS LIBRARY_EXTRA_CPPFLAGS LIB_LF WITH_MAGICK_PLUS_PLUS_TRUE WITH_MAGICK_PLUS_PLUS_FALSE CCMALLOCDelegate LIB_MATH LIB_THREAD HasZLIB_TRUE HasZLIB_FALSE LIB_ZLIB HasBZLIB_TRUE HasBZLIB_FALSE LIB_BZLIB X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HasX11_TRUE HasX11_FALSE LIB_X11 LIB_XEXT LIB_DL HasDPS_TRUE HasDPS_FALSE LIB_DPS HasFPX_TRUE HasFPX_FALSE LIB_FPX HasLCMS_TRUE HasLCMS_FALSE LIB_LCMS HasPNG_TRUE HasPNG_FALSE LIB_PNG HasJPEG_TRUE HasJPEG_FALSE LIB_JPEG HasJP2_TRUE HasJP2_FALSE LIB_JP2 HasGS_TRUE HasGS_FALSE LIB_GS freetype_config HasTTF_TRUE HasTTF_FALSE LIB_TTF HasTIFF_TRUE HasTIFF_FALSE LIB_TIFF HasJBIG_TRUE HasJBIG_FALSE LIB_JBIG xml2_config HasXML_TRUE HasXML_FALSE LIB_XML HasWMF_TRUE HasWMF_FALSE LIB_WMF LIB_WMF_DEPS MagickLibPath MagickModulesPath MagickSharePath AutotraceDecodeDelegate BZIPDelegate BrowseDelegate CGMDecodeDelegate CatDelegate DOTDecodeDelegate DVIDecodeDelegate EchoDelegate EditorDelegate FIGDecodeDelegate GnuplotDecodeDelegate HPGLDecodeDelegate HTMLDecodeDelegate ILBMDecodeDelegate ILBMEncodeDelegate LPDelegate LPRDelegate LZWDecodeDelegate LZWEncodeDelegate LaunchDelegate MANDelegate MPEGDecodeDelegate MPEGEncodeDelegate MVDelegate PGPDecodeDelegate POVDelegate PSDelegate RADDecodeDelegate RLEEncodeDelegate RMDelegate SCANDecodeDelegate TXTDelegate WMFDecodeDelegate WWWDecodeDelegate ZipDelegate PrintDelegate TXT2HTML HasTXT2HTML_TRUE HasTXT2HTML_FALSE windows_font_dir ghostscript_font_dir type_include_files ConvertDelegate MogrifyDelegate ShowImageDelegate GSMonoDevice GSPDFDevice GSPSDevice GSColorDevice GSEPSDevice PERL WITH_PERL_TRUE WITH_PERL_FALSE WITH_PERL_STATIC_TRUE WITH_PERL_STATIC_FALSE WITH_PERL_DYNAMIC_TRUE WITH_PERL_DYNAMIC_FALSE MAGICKLIB DELEGATES MAGICK_DEP_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20591,8 +20591,8 @@ then
 fi
 
 #
-# Enable support for modules
-# Only support modules if we are building shared libraries
+# Enable support for building loadable modules
+#
 
 # Check whether --with-modules or --without-modules was given.
 if test "${with_modules+set}" = set; then
@@ -20601,9 +20601,21 @@ if test "${with_modules+set}" = set; then
 else
   with_modules='no'
 fi;
-if test "$with_modules" != 'no' && test "$libtool_build_shared_libs" = 'no'
-then
-  with_modules='no'
+
+# Only allow building loadable modules if we are building shared libraries
+if test "$with_modules" != 'no' ; then
+  if test "$libtool_build_shared_libs" = 'no' ; then
+    { echo "$as_me:$LINENO: WARNING: Modules may only be built if building shared libraries is enabled." >&5
+echo "$as_me: WARNING: Modules may only be built if building shared libraries is enabled." >&2;}
+    with_modules='no'
+  fi
+fi
+if test "$with_modules" != 'no' ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define BuildMagickModules 1
+_ACEOF
+
 fi
 
 
@@ -20615,11 +20627,28 @@ else
   WITH_MODULES_FALSE=
 fi
 
-if test "$with_modules" != 'no'
-then
+
+# Enable building/use of libltdl if we are building shared libraries regardless
+# of whether modules are built or not.
+with_ltdl='no'
+if test "$libtool_build_shared_libs" != 'no' ; then
+  with_ltdl='yes'
+fi
+
+
+
+if test "$with_ltdl" != 'no'; then
+  WITH_LTDL_TRUE=
+  WITH_LTDL_FALSE='#'
+else
+  WITH_LTDL_TRUE='#'
+  WITH_LTDL_FALSE=
+fi
+
+if test "$with_ltdl" != 'no' ; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasLTDL
+#define HasLTDL 1
 _ACEOF
 
 
@@ -24636,7 +24665,7 @@ echo "${ECHO_T}$ac_cv_lib_pthread_pthread_attr_init" >&6
 if test $ac_cv_lib_pthread_pthread_attr_init = yes; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasPTHREADS
+#define HasPTHREADS 1
 _ACEOF
 
      LIB_THREAD="-lpthread"
@@ -25189,7 +25218,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
       LIBS="$LIB_ZLIB $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasZLIB
+#define HasZLIB 1
 _ACEOF
 
       echo "$as_me:$LINENO: result: yes" >&5
@@ -25496,7 +25525,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
       LIBS="$LIB_BZLIB $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasBZLIB
+#define HasBZLIB 1
 _ACEOF
 
       echo "$as_me:$LINENO: result: yes" >&5
@@ -26730,7 +26759,7 @@ then
 
 
 cat >>confdefs.h <<\_ACEOF
-#define HasX11
+#define HasX11 1
 _ACEOF
 
   echo "$as_me:$LINENO: checking for XShmAttach in -lXext" >&5
@@ -26848,7 +26877,7 @@ echo "${ECHO_T}$ac_cv_lib_Xext_XShmAttach" >&6
 if test $ac_cv_lib_Xext_XShmAttach = yes; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasSharedMemory
+#define HasSharedMemory 1
 _ACEOF
 
 fi
@@ -26968,7 +26997,7 @@ echo "${ECHO_T}$ac_cv_lib_Xext_XShapeCombineMask" >&6
 if test $ac_cv_lib_Xext_XShapeCombineMask = yes; then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasShape
+#define HasShape 1
 _ACEOF
 
 fi
@@ -27349,7 +27378,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_DPS $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasDPS
+#define HasDPS 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -27610,7 +27639,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_FPX $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasFPX
+#define HasFPX 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -28011,7 +28040,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_LCMS $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasLCMS
+#define HasLCMS 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -28258,7 +28287,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_PNG $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasPNG
+#define HasPNG 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -28978,7 +29007,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_JPEG $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasJPEG
+#define HasJPEG 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -29225,7 +29254,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_JP2 $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasJP2
+#define HasJP2 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -29751,7 +29780,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_GS $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasGS
+#define HasGS 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -29798,7 +29827,7 @@ fi
 #     else
 # 	LIB_MPEG2='-lmpeg2'
 # 	LIBS="$LIB_MPEG2 $LIBS"
-# 	AC_DEFINE(HasMPEG2,,Define if you have MPEG2 library)
+# 	AC_DEFINE(HasMPEG2,1,Define if you have MPEG2 library)
 # 	AC_MSG_RESULT(yes)
 # 	have_mpeg2='yes'
 #     fi
@@ -30111,7 +30140,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	    LIBS="$LIB_TTF $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasTTF
+#define HasTTF 1
 _ACEOF
 
 	    echo "$as_me:$LINENO: result: yes" >&5
@@ -30494,7 +30523,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_TIFF $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasTIFF
+#define HasTIFF 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -30689,7 +30718,7 @@ fi
 #     else
 #         LIB_HDF='-ldf'
 #         LIBS="$LIB_HDF $LIBS"
-#         AC_DEFINE(HasHDF,,Define if you have HDF library)
+#         AC_DEFINE(HasHDF,1,Define if you have HDF library)
 #         AC_MSG_RESULT(yes)
 #         have_hdf='yes'
 #     fi
@@ -30923,7 +30952,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_JBIG $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasJBIG
+#define HasJBIG 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -31226,7 +31255,7 @@ echo "${ECHO_T}no -- some components failed test" >&6
 	LIBS="$LIB_XML $LIBS"
 
 cat >>confdefs.h <<\_ACEOF
-#define HasXML
+#define HasXML 1
 _ACEOF
 
 	echo "$as_me:$LINENO: result: yes" >&5
@@ -31468,7 +31497,7 @@ fi
     then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasWMFlite
+#define HasWMFlite 1
 _ACEOF
 
 
@@ -31547,7 +31576,7 @@ fi
       then
 
 cat >>confdefs.h <<\_ACEOF
-#define HasWMF
+#define HasWMF 1
 _ACEOF
 
         LIB_WMF='-lwmf'
@@ -33799,6 +33828,13 @@ echo "$as_me: error: conditional \"WITH_MODULES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${WITH_LTDL_TRUE}" && test -z "${WITH_LTDL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_LTDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_LTDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${MAINTAINER_MODE_TRUE}" && test -z "${MAINTAINER_MODE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MAINTAINER_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -34615,6 +34651,8 @@ s,@LIBTOOL@,$LIBTOOL,;t t
 s,@LIBTOOL_DEPS@,$LIBTOOL_DEPS,;t t
 s,@WITH_MODULES_TRUE@,$WITH_MODULES_TRUE,;t t
 s,@WITH_MODULES_FALSE@,$WITH_MODULES_FALSE,;t t
+s,@WITH_LTDL_TRUE@,$WITH_LTDL_TRUE,;t t
+s,@WITH_LTDL_FALSE@,$WITH_LTDL_FALSE,;t t
 s,@DLLDFLAGS@,$DLLDFLAGS,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
