Enhancements for Cygwin and MinGW.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1906,24 +1906,6 @@ CPPFLAGS_INITIAL=$CPPFLAGS
 LDFLAGS_INITIAL=$LDFLAGS
 LIBS_INITIAL=$LIBS
 
-# Set native_win32_build to 'yes' if building under MinGW
-native_win32_build='no'
-case "${host_os}" in
-  mingw* )
-    native_win32_build='yes'
-    ;;
-esac
-
-
-if test "$native_win32_build" != 'no'; then
-  WIN32_TRUE=
-  WIN32_FALSE='#'
-else
-  WIN32_TRUE='#'
-  WIN32_FALSE=
-fi
-
-
 #
 # Evaluate shell variable equivalents to Makefile directory variables
 #
@@ -3302,12 +3284,49 @@ fi
 
 
 LIB_GDI32=''
-if test "$native_win32_build" = 'yes'
+native_win32_build='no'
+case "${host_os}" in
+  cygwin* )
+    LIB_GDI32='-lgdi32'
+    ;;
+  mingw* )
+    native_win32_build='yes'
+    LIB_GDI32='-lgdi32'
+    ;;
+esac
+if test -n "$LIB_GDI32"
 then
-  LIB_GDI32='-lgdi32'
+
+cat >>confdefs.h <<\_ACEOF
+#define HasWINGDI32 1
+_ACEOF
 
 fi
 
+
+
+if test -n "$LIB_GDI32" ; then
+  HasWINGDI32_TRUE=
+  HasWINGDI32_FALSE='#'
+else
+  HasWINGDI32_TRUE='#'
+  HasWINGDI32_FALSE=
+fi
+
+
+
+if test "$native_win32_build" != 'no' ; then
+  WIN32_NATIVE_TRUE=
+  WIN32_NATIVE_FALSE='#'
+else
+  WIN32_NATIVE_TRUE='#'
+  WIN32_NATIVE_FALSE=
+fi
+
+
+#
+# Compiler flags tweaks
+#
 if test "${GCC}" != "yes"
 then
   case "${host}" in
@@ -3765,7 +3784,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3768 "configure"' > conftest.$ac_ext
+  echo '#line 3787 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7669,7 +7688,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7672 "configure"
+#line 7691 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7767,7 +7786,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7770 "configure"
+#line 7789 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10916,7 +10935,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10919 "configure"
+#line 10938 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11014,7 +11033,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11017 "configure"
+#line 11036 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13674,7 +13693,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13677 "configure"
+#line 13696 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13772,7 +13791,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13775 "configure"
+#line 13794 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15288,7 +15307,12 @@ then
     if test "$with_modules" = 'yes'
     then
       LIBRARY_EXTRA_CPPFLAGS="$LIBRARY_EXTRA_CPPFLAGS -D_MAGICKMOD_"
+    else
+      MODULE_EXTRA_CPPFLAGS="$MODULE_EXTRA_CPPFLAGS -D_MAGICKLIB_"
     fi
+
+  else
+    CPPFLAGS="$CPPFLAGS -D_LIB"
 
   fi
   if test "$with_threads" = 'yes'
@@ -29426,17 +29450,24 @@ fi
 
 DEFS=-DHAVE_CONFIG_H
 
-if test -z "${WIN32_TRUE}" && test -z "${WIN32_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"WIN32\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"WIN32\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HasWINGDI32_TRUE}" && test -z "${HasWINGDI32_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HasWINGDI32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HasWINGDI32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WIN32_NATIVE_TRUE}" && test -z "${WIN32_NATIVE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WIN32_NATIVE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WIN32_NATIVE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -30155,8 +30186,6 @@ s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
-s,@WIN32_TRUE@,$WIN32_TRUE,;t t
-s,@WIN32_FALSE@,$WIN32_FALSE,;t t
 s,@PREFIX_DIR@,$PREFIX_DIR,;t t
 s,@EXEC_PREFIX_DIR@,$EXEC_PREFIX_DIR,;t t
 s,@BIN_DIR@,$BIN_DIR,;t t
@@ -30190,6 +30219,10 @@ s,@CPP@,$CPP,;t t
 s,@LD@,$LD,;t t
 s,@LN_S@,$LN_S,;t t
 s,@LIB_GDI32@,$LIB_GDI32,;t t
+s,@HasWINGDI32_TRUE@,$HasWINGDI32_TRUE,;t t
+s,@HasWINGDI32_FALSE@,$HasWINGDI32_FALSE,;t t
+s,@WIN32_NATIVE_TRUE@,$WIN32_NATIVE_TRUE,;t t
+s,@WIN32_NATIVE_FALSE@,$WIN32_NATIVE_FALSE,;t t
 s,@INCLTDL@,$INCLTDL,;t t
 s,@LIBLTDL@,$LIBLTDL,;t t
 s,@ECHO@,$ECHO,;t t
