* magick/Makefile.am (MAGICK_BASE_SRCS): Remove mention of non-existent mmath.h. * configure.ac: AC_LIBTOOL_SETUP is an internal macro and must not be used externally (will be pulled in automatically). * PerlMagick/Makefile.am: Missing file needed to be committed to CVS. * tests/Makefile.am (TESTS_TIFF_XFAIL_TESTS): EPT and PTIF tests are expected to fail if libtiff is missing.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23498,74 +23498,6 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
-  # Test for C++ compiler __func__ support
- if test "$ac_cv_have_CPP__func__" != 'yes' ; then
-  echo "$as_me:$LINENO: checking for C++ compiler __func__ support" >&5
-echo $ECHO_N "checking for C++ compiler __func__ support... $ECHO_C" >&6
-if test "${ac_cv_have_CPP__func__+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-int
-main ()
-{
-
-  const char *func=__func__;
-  return (func != 0 ? 0 : 1);
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-    ac_cv_have_CPP__func__='yes'
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_have_CPP__func__='no'
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $ac_cv_have_CPP__func__" >&5
-echo "${ECHO_T}$ac_cv_have_CPP__func__" >&6
-
-  if test "$ac_cv_have_CPP__func__" = 'yes' ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAS_CPP__func__ 1
-_ACEOF
-
-  fi
- fi
-
 # Full set of headers used ...
 # algorithm cctype cerrno cmath cstdio cstdlib cstring ctime exception
 # functional iomanip iosfwd iostream iterator list string strstream utility
@@ -24987,6 +24919,75 @@ _ACEOF
 
 fi
 rm -rf SunWS_cache
+
+
+ # Test for C++ compiler __func__ support
+ if test "$ac_cv_have_CPP__func__" != 'yes' ; then
+  echo "$as_me:$LINENO: checking for C++ compiler __func__ support" >&5
+echo $ECHO_N "checking for C++ compiler __func__ support... $ECHO_C" >&6
+if test "${ac_cv_have_CPP__func__+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  const char *func=__func__;
+  return (func != 0 ? 0 : 1);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+    ac_cv_have_CPP__func__='yes'
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_CPP__func__='no'
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_CPP__func__" >&5
+echo "${ECHO_T}$ac_cv_have_CPP__func__" >&6
+
+  if test "$ac_cv_have_CPP__func__" = 'yes' ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAS_CPP__func__ 1
+_ACEOF
+
+  fi
+ fi
 
  ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
