Split nt.c/nt.h into ntbase.c/.h & ntfeature.c/.h

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3286,8 +3286,10 @@ fi
 
 LIB_GDI32=''
 native_win32_build='no'
+cygwin_build='no'
 case "${host_os}" in
   cygwin* )
+    cygwin_build='yes'
     LIB_GDI32='-lgdi32'
     ;;
   mingw* )
@@ -3317,11 +3319,21 @@ fi
 
 
 if test "${native_win32_build}" = 'yes' ; then
-  WIN32_NATIVE_TRUE=
-  WIN32_NATIVE_FALSE='#'
+  WIN32_NATIVE_BUILD_TRUE=
+  WIN32_NATIVE_BUILD_FALSE='#'
 else
-  WIN32_NATIVE_TRUE='#'
-  WIN32_NATIVE_FALSE=
+  WIN32_NATIVE_BUILD_TRUE='#'
+  WIN32_NATIVE_BUILD_FALSE=
+fi
+
+
+
+if test "${cygwin_build}" = 'yes' ; then
+  CYGWIN_BUILD_TRUE=
+  CYGWIN_BUILD_FALSE='#'
+else
+  CYGWIN_BUILD_TRUE='#'
+  CYGWIN_BUILD_FALSE=
 fi
 
 
@@ -5547,7 +5559,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 5550 "configure"
+#line 5562 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6862,7 +6874,6 @@ bsdi4*)
 cygwin* | mingw* | pw32*)
   lt_cv_deplibs_check_method='file_magic file format pei*-i386(.*architecture: i386)?'
   lt_cv_file_magic_cmd='$OBJDUMP -f'
-  lt_cv_deplibs_check_method=pass_all
   ;;
 
 darwin* | rhapsody*)
@@ -6876,7 +6887,6 @@ darwin* | rhapsody*)
     lt_cv_file_magic_test_file='/usr/lib/libSystem.dylib'
     ;;
   esac
-  lt_cv_deplibs_check_method=pass_all
   ;;
 
 freebsd*)
@@ -7062,7 +7072,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7063 "configure"' > conftest.$ac_ext
+  echo '#line 7075 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11003,7 +11013,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11004 "configure"
+#line 11016 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11101,7 +11111,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11102 "configure"
+#line 11114 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14250,7 +14260,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14251 "configure"
+#line 14263 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14348,7 +14358,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14349 "configure"
+#line 14361 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17008,7 +17018,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17009 "configure"
+#line 17021 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17106,7 +17116,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17107 "configure"
+#line 17119 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -32392,10 +32402,17 @@ echo "$as_me: error: conditional \"HasWINGDI32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${WIN32_NATIVE_TRUE}" && test -z "${WIN32_NATIVE_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"WIN32_NATIVE\" was never defined.
+if test -z "${WIN32_NATIVE_BUILD_TRUE}" && test -z "${WIN32_NATIVE_BUILD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WIN32_NATIVE_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"WIN32_NATIVE\" was never defined.
+echo "$as_me: error: conditional \"WIN32_NATIVE_BUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${CYGWIN_BUILD_TRUE}" && test -z "${CYGWIN_BUILD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"CYGWIN_BUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"CYGWIN_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -33164,8 +33181,10 @@ s,@LN_S@,$LN_S,;t t
 s,@LIB_GDI32@,$LIB_GDI32,;t t
 s,@HasWINGDI32_TRUE@,$HasWINGDI32_TRUE,;t t
 s,@HasWINGDI32_FALSE@,$HasWINGDI32_FALSE,;t t
-s,@WIN32_NATIVE_TRUE@,$WIN32_NATIVE_TRUE,;t t
-s,@WIN32_NATIVE_FALSE@,$WIN32_NATIVE_FALSE,;t t
+s,@WIN32_NATIVE_BUILD_TRUE@,$WIN32_NATIVE_BUILD_TRUE,;t t
+s,@WIN32_NATIVE_BUILD_FALSE@,$WIN32_NATIVE_BUILD_FALSE,;t t
+s,@CYGWIN_BUILD_TRUE@,$CYGWIN_BUILD_TRUE,;t t
+s,@CYGWIN_BUILD_FALSE@,$CYGWIN_BUILD_FALSE,;t t
 s,@INSTALL_LTDL_TRUE@,$INSTALL_LTDL_TRUE,;t t
 s,@INSTALL_LTDL_FALSE@,$INSTALL_LTDL_FALSE,;t t
 s,@CONVENIENCE_LTDL_TRUE@,$CONVENIENCE_LTDL_TRUE,;t t
